### ISSUE TITLE
Missing releases on crates.io

### ISSUE THREAD

**Issue by thadouk** [paritytech/ss58-registry#222]
Releases 1.48, 1.49 and 1.50 haven't been published on crates.io
- https://crates.io/crates/ss58-registry/versions
- https://www.npmjs.com/package/@substrate/ss58-registry

Would it be possible to publish 1.50 release on crates.io?

**Comment by bkchr** [comment]
@alvicsam could you help here? I think the release job is just broken

**Comment by alvicsam** [comment]
Sorry for that. Currently I released crates manually and will fix the CI later.

**Comment by thadouk** [comment]
Thank you for addressing this
