### ISSUE TITLE
Publish to npmjs registry

### ISSUE THREAD

**Issue by jacogr** [paritytech/ss58-registry#35]
I didn't want to include this in https://github.com/paritytech/ss58-registry/issues/28 which I suspect is already underway. This is also about publishing, but slightly different.

1. After https://github.com/paritytech/ss58-registry/pull/33 we can now align the version of the root package.json with the Rust sources. To do so you can run `npm run alignVersion`. The suggested approach here is that after we tag/create a version (as per #28), we run this command and then can push the changes back to GitHub.

2. After https://github.com/paritytech/ss58-registry/pull/34 we can now publish the JS packages to npmjs as well. Basically  run `npm run alignVersion` and then `npm run build`, which will create the outputs and then we can publish with `cd npm_dist && npm publish --access public`

The npm publish here should be no different from what we do in other `@substrate` packages (just not that familiar with the process generally employed for these on Parity CI)

**Comment by bkchr** [comment]
If we can do #28 as a github action as well, I'm in

**Comment by alvicsam** [comment]
I'm planning to do https://github.com/paritytech/ss58-registry/issues/28 using gitlab ci. I'll add this task to [the ci/cd issue tracker](https://github.com/paritytech/ci_cd/issues)
