### ISSUE TITLE
Support Testnets

### ISSUE THREAD

**Issue by bkchr** [paritytech/ss58-registry#85]
We don't provide custom prefixes to testnets, instead these testnets should use `42` as prefix. However, some people still would like to have testnets inside the ss58 json file, because polkadot-js for example seems to use this as a canonical source of networks. See [this](https://github.com/paritytech/ss58-registry/pull/84#issuecomment-1067596726) for some more context.

Adding support for these testnets should be fairly simple. We would not support the reverse lookup, aka `42` would always return `Substrate`, but that should be okay. 

@jacogr WDYT?

**Comment by jacogr** [comment]
I actually actively filter out all testnets, so they don't appear in any lists. There are some testnets in the current registry, e.g. 

https://github.com/paritytech/ss58-registry/blob/eb89e2f31b8fb7fc8a9a41ea15d878b64055aa98/ss58-registry.json#L202-L210 

For those I keep a list and match them to filter out (also matching on text such as `-testnet`) - 

https://github.com/polkadot-js/common/blob/6dc79a0b7c0002419d861235ba9b20d5d3a5eefa/packages/networks/src/defaults.ts#L40

**Comment by bkchr** [comment]
Okay, these testnets should not have made it into the json :see_no_evil: 

You are right that they should not have their own prefix. I would more like to support them in the json, but they will use `42` as prefix. We could probably introduce some new optional `testnet: true` field for each entry. 

We should probably not add every test net, but the main ones like Westend and Rococo and some of the community. 

If we have the `testnet` identifier, you should be able to filter them better in the UI?

**Comment by Nick-1979** [comment]
Hello everyone,

Thank you for the comments, as far as I understand, adding Westend should not make any issues for Polkadot js extension, moreover, Westend is already available on Polkadot.js.org.

What I need is to have Westend in "Polkadot js Plus extension", Now, I **manually** add it to the json file, and every other developers to build the code from the source need to add it manually which is cumbersome.

I believe supporting major testnets like Westend, which obviously have no cost for users, let them to try/learn different features/concepts of Polkadot ecosystem (like bonding, unbonding, chill, redeem, nominate , existential deposit, transferAll, etc.) that we know is sometimes complicated. This will definitely help to grow the community.

Cheers,
   Kami

**Comment by jacogr** [comment]
Yes. With a flag I will just adjust the filtering, so it is no cost at all. (And better since the existing filters can then be made explicit)

**Comment by itsbirdo** [comment]
Closing this as no discussion after 2 years~
